spring:
  datasource:
    # mysql: com.mysql.cj.jdbc.Driver
    # mariadb: org.mariadb.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    # mysql: jdbc:mysql://localhost:3306/testdb
    # mariadb: jdbc:mariadb://localhost:3306/testdb
    url: jdbc:mariadb://localhost:3306/winter
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
